#ifndef DEF_PHYSIC_BACKEND_HPP
#define DEF_PHYSIC_BACKEND_HPP

#cmakedefine SUSHI_PHYSIC_BACKEND "@SUSHI_PHYSIC_BACKEND@"
#cmakedefine SUSHI_PHYSIC_BACKEND_PHYSX
#cmakedefine SUSHI_PHYSIC_BACKEND_BULLET

#endif